global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts.yml"

scrape_configs:
  # API Node.js
  - job_name: 'crypto-api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Collector
  - job_name: 'crypto-collector'
    static_configs:
      - targets: ['collector:9091']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
